spring:
  application:
    name: store
  datasource:
    url: jdbc:postgres://localhost:5432/store_api?createDatabaseIfNotExist=true
    username: postgres
    password: root
  jpa:
    show-sql: true
